ubtue/ub_tools

.gitignore, cpp/Makefile, cpp/create_full_text_db.cc, cpp/download_test.cc, cpp/lib/HtmlUtil.cc, cpp/lib/HtmlUtil.h, cpp/lib/IdbPager.cc, cpp/lib/IdbPager.h, cpp/lib/Makefile, cpp/lib/SmartDownloader.cc
Bitte gründlich und kritisch betrachten.
=> Added support for downloading of all pages of Diglit documents.

cronjobs/fetch_marc_updates.py
if a file is not on the BSZ FTP server.)
=> Fixed incorrect error abort. (We should not bail out but continue.)

cpp/augment_bible_references.cc, cpp/krimdok_marc_pipeline.sh, cpp/lib/MarcUtil.cc, cpp/marc_info.cc, cronjobs/Makefile, cronjobs/create_tarball.py, cronjobs/handle_partial_updates.py, cronjobs/purge_old_data.py, cronjobs/util.py
Now "marc_info" also uses this.
=> Improved record integrity checking in MarcUtil::RecordSeemsCorrect().

cpp/merge_differential_and_full_marc_updates.cc
- The LOEPPN is needed in initial_marc_pipeline
- If we have nothing to do, do nothing!
=> Don't remove LOEPPN

cronjobs/fetch_marc_updates.py
data dump has been downloaded was always being created.
=> Fixed a problem where the flag file indicating that a complete

cpp/update_full_text_db.cc
of the behaviour that we actually wanted.
=> Fixed an incorrect enum value which indicated the opposite

solrmarc_mixin/src/de/unituebingen/ub/ubtools/solrmarcMixin/TuelibMixin.java
will blow up sometime after I am dead.)
=> Handle dates from the last century properly.  (Obviously this

cpp/marc_filter.cc
=> Fixed a bug where invocations with --remove-fields removed all records

cpp/normalise_urls.cc
=> Remove bare duplicate 856u entries, IOW, those that are also found as

cpp/data/subscriptions_email.ixtheo.template, cpp/data/subscriptions_email.relbib.template, cpp/new_journal_alert.cc
- use "container_ids_and_titles" instead of "journal_issue"
- changed "journal_title" to "series_title"
- uses JSON.h
=> new journal alert:

docker/ixtheo/Dockerfile, docker/krimdok/Dockerfile, solrmarc_mixin/src/de/unituebingen/ub/ubtools/solrmarcMixin/TuelibMixin.java
=> getSortableTitle without unicode quotation marks

cpp/new_journal_alert.cc
- treat "normal" as "verbose" (normal logs have always been empty)
- "debug" now also means that db will not be updated
=> more logging for ubtue/tuefind#210
=> new_journal_alert changes

cpp/add_isbns_or_issns_to_articles.cc, cpp/data/zts_harvester.conf
=> New KrimDok zts_harvester entries

cpp/find_missing_metadata.cc, cpp/zts_harvester.cc, cpp/zts_harvester_pipeline.sh
find_missing_metadata fails on missed expectations
=> Add zts_harvester delivery pipeline

cpp/lib/include/Zotero.h, cpp/lib/src/Zotero.cc, cpp/zotero_cgi.cc, cpp/zts_harvester.cc
Default to RSSHarvesterMode::TEST for RSS feeds until the code is refactored
=> Track delivery mode when harvesting URLs

cpp/data/zts_harvester.conf, cpp/lib/include/FileUtil.h, cpp/lib/include/JournalConfig.h, cpp/lib/include/Zotero.h, cpp/lib/src/FileUtil.cc, cpp/lib/src/JournalConfig.cc, cpp/lib/src/Zotero.cc, cpp/rss_harvester.cc, cpp/zeder_to_zotero_importer.cc, cpp/zeder_to_zotero_pipeline.cc, cpp/zotero_cgi.cc, cpp/zts_harvester.cc
Refactor Zeder/Zotero classes to use JournalConfig
=> JournalConfig: Central repository for journal-related INI config data

cpp/lib/include/BSZUpload.h, cpp/zts_harvester.cc, cpp/zts_harvester_pipeline.sh
zts_harvester_pipeline: update to support output directories/groups
=> zts_harvester: fix delivery mode parsing

cpp/rewrite_ssoar.cc
=> rewrite_ssoar: remove license field 540

java/solrmarc_mixin/src/de/unituebingen/ub/ubtools/solrmarcMixin/TuelibMixin.java
see ubtue/ixTheo#640 and ubtue/tuefind#408
=> avoid "DictionaryEntryOrArticle" and "Article" at the same time

cronjobs/initiate_marc_pipeline.py
DEPENDENCY: please merge ubtue/tuefind#441 before merging this one!
=> initiate_marc_pipeline now also imports authority data

cpp/data/zts_harvester.conf, cpp/lib/src/Zotero.cc, cpp/zotero_cgi.cc
note: print and online issn for Estudios Eclesiasticos have the same values in Zeder.
=> DatenProbleme

cpp/data/zts_harvester.conf
=> zts_harvester: removed "Psychology of religion and spirituality" - not fit for automatic harvesting

cpp/data/installer/ub_tools.sql, cpp/data/zts_harvester.conf, cpp/lib/src/Zotero.cc, docker/squid/Dockerfile, docker/squid/build.sh, docker/squid/squid.conf, docker/squid/systemd/squid.service, docker/squid/systemd/start.sh, docker/squid/systemd/stop.sh
… to TIMESTAMP for mariadb compatibility, similar to rss_items.creation_datetime (problem: DATETIME default CURRENT_TIMESTAMP or NOW() is incompatible with mariadb)
=> DatenProbleme + mariaDB scheme problem

cpp/data/zts_harvester.conf
set Journal of Law and Religion (0748-0814), Journal of Religion and Violence (2159-6808) und Reviews in religion and theology (1350-7303) to TEST delivery mode
=> zts_harvester: turn on test delivery for the first 3 (IxTheo) journals

cpp/lib/src/Zotero.cc
=> Zotero: flag as review if an ISBN appears in the title

cpp/data/zts_harvester.conf, cpp/lib/include/Zotero.h, cpp/lib/src/Zotero.cc, cpp/zts_harvester.cc
update zts_harvester.conf. refs ubtue/DatenProbleme#130.
=> zts_harvester/zotero: add the ability to exclude records based on regex filters

cpp/data/zts_harvester.conf, cpp/find_missing_metadata.cc
zts_harvester: add exclusion filter
=> find_missing_metadata: output report to stdout

cpp/data/zeder_to_zotero_importer.conf, cpp/data/zts_harvester.conf, cpp/lib/src/Zotero.cc, cpp/zeder_to_zotero_importer.cc
Zotero: fix regex for matching bad strptime errors
zeder_to_zotero_importer: add config entry to  ignore warnings of ISSNs and PPNs during config generation
=> zts_harvester: add 16 IxTheo journals (Peeters)

cpp/lib/src/Zotero.cc
=> Zotero: add MARC field 655 for reviews

cpp/cgi_progs/zotero_cgi.cc, cpp/data/zts_harvester.conf, cpp/lib/src/Zeder.cc, cpp/zeder_to_zotero_conversion_tools.cc, cpp/zts_harvester.cc
zeder_to_zotero_conversion_tools: anneal flavour parsing, make Zeder comments optional
zotero_cgi: do not discard records that ahve already been delivered
zts_harvester: add 1 Ixtheo journal (Wiley)
=> Zeder: fix flavour parsing

cpp/data/zts_harvester.conf, cpp/lib/include/Zotero.h, cpp/lib/src/NGram.cc, cpp/lib/src/Zotero.cc, cpp/zts_harvester.cc
refs ubtue/DatenProbleme#174, ubtue/DatenProbleme#178, ubtue/DatenProbleme#175, ubtue/DatenProbleme#158, ubtue/DatenProbleme#139, ubtue/DatenProbleme#172,  ubtue/DatenProbleme#157, ubtue/DatenProbleme#155, ubtue/DatenProbleme#184, ubtue/DatenProbleme#169
=> DatenProbleme fixes and minor additions

cpp/data/zts_harvester.conf, cpp/lib/include/MARC.h, cpp/lib/include/Zotero.h, cpp/lib/src/Zotero.cc
refs ubtue/DatenProbleme#155, ubtue/DatenProbleme#139
=> Zotero: use the ISSN-langauge map only when we cannot detect the language automatically

cpp/lib/src/Zotero.cc
=> See Datenprobleme #197.

cpp/cgi_progs/zotero_cgi.cc, cpp/data/installer/ub_tools.sql, cpp/data/zts_harvester.conf, cpp/lib/include/BSZUpload.h, cpp/lib/include/JournalConfig.h, cpp/lib/include/Zeder.h, cpp/lib/include/Zotero.h, cpp/lib/src/BSZUpload.cc, cpp/lib/src/JournalConfig.cc, cpp/lib/src/Zeder.cc, cpp/lib/src/Zotero.cc, cpp/zeder_to_zotero_conversion_tools.cc, cpp/zts_harvester.cc
=> Zotero changes

cpp/cgi_progs/zotero_cgi.cc, cpp/data/zts_harvester.conf, cpp/lib/include/ExecUtil.h, cpp/lib/include/Zotero.h, cpp/lib/src/ExecUtil.cc, cpp/lib/src/Zotero.cc, cpp/zts_harvester.cc, cpp/zts_harvester_delivery_pipeline.sh
refs ubtue/DatenProbleme#175, ubtue/DatenProbleme#173, ubtue/DatenProbleme#170
=> Datenprobleme fixes

cpp/data/zts_harvester.conf, cpp/lib/src/Zotero.cc, git-config/hooks/post-merge
refs ubtue/DatenProbleme#197, ubtue/DatenProbleme#192
=> Zotero: more MARC format fixes for reviews

cpp/add_journal_subscription.cc, cpp/clean_tag_db.cc, cpp/convert_tags_to_keywords.cc, cpp/data/bibleRef/books_of_the_bible_to_canonical_form.map, cpp/lib/include/DbConnection.h, cpp/lib/include/VuFind.h, cpp/lib/src/DbConnection.cc, cpp/lib/src/VuFind.cc, cpp/mysql_schema_diff.cc, cpp/new_journal_alert.cc, cpp/patch_up_ppns_for_k10plus.cc, cpp/pipelines/export_subsystem_ids_to_db.cc, cpp/pipelines/merge_print_and_online.cc, cpp/set_tad_access_flag.cc, cpp/test/vufind_db_test.cc, git-config/hooks/post-merge
+mysql_schema_diff now tries to autodetect credentials for ub_tools + vufind
=> VuFind getMysqlURL now returns string

cpp/lib/src/Zotero.cc
=> Zotero: fix authors' title encoding in field 700/100

cpp/data/zts_harvester.conf, cpp/lib/include/Zotero.h, cpp/lib/src/Zotero.cc, cpp/zts_harvester.cc
zts_harvester: update config for 'Journal of church and state'
refs ubtue/DatenProbleme#183
=> Zotero: add new config entry to remove fields

cpp/lib/src/Zotero.cc
=> Zotero: normalize page number ranges

cpp/canon_law_to_codes_tool.cc, cpp/data/zts_harvester.conf, cpp/lib/include/MARC.h, cpp/lib/src/MARC.cc, cpp/lib/src/SyndicationFormat.cc, cpp/lib/src/XMLParser.cc, cpp/lib/src/Zotero.cc, cpp/pipelines/.gitignore, cpp/pipelines/augment_canones_references.cc
refs ubtue/DatenProbleme#135, ubtue/DatenProbleme#170, ubtue/DatenProbleme#183, ubtue/DatenProbleme#199
=> Bug fixes and additions

cpp/lib/src/Zotero.cc
refs ubtue/DatenProbleme#197, ubtue/DatenProbleme#148
=> Zotero fixes

cpp/lib/include/DbConnection.h
Add host to avoid Ubuntu/MySQL compatibility problem ("Can't find any matching row in the user table")
=> mySQLGrantAllPrivileges 

cpp/lib/src/BSZTransform.cc, cpp/zts_harvester.cc
=> Zotero: add command line param for testing single URLs

cpp/lib/src/Zotero.cc
refs ubtue/DatenProbleme#229, ubtue/DatenProbleme#228, ubtue/DatenProbleme#233
=> Zotero MARC fixes and changes

cpp/data/zts_harvester.conf, cpp/lib/src/Zotero.cc, cpp/zts_harvester.cc
refs ubtue/DatenProbleme#237, ubtue/DatenProbleme#238, ubtue/DatenProbleme#240, ubtue/DatenProbleme#244, ubtue/DatenProbleme#268, ubtue/DatenProbleme#229, ubtue/DatenProbleme#247, ubtue/DatenProbleme#270, ubtue/DatenProbleme#269, ubtue/DatenProbleme#267, ubtue/DatenProbleme#242
=> More fixes

cpp/data/zts_harvester.conf
refs ubtue/DatenProbleme#275, ubtue/DatenProbleme#277, ubtue/DatenProbleme#279, ubtue/DatenProbleme#281, ubtue/DatenProbleme#282, ubtue/DatenProbleme#284, ubtue/DatenProbleme#286, ubtue/DatenProbleme#287, ubtue/DatenProbleme#288, ubtue/DatenProbleme#293, ubtue/DatenProbleme#296, ubtue/DatenProbleme#297, ubtue/DatenProbleme#298, ubtue/DatenProbleme#334, ubtue/DatenProbleme#331, ubtue/DatenProbleme#246, ubtue/DatenProbleme#330, ubtue/DatenProbleme#319, ubtue/DatenProbleme#314, ubtue/DatenProbleme#312, ubtue/DatenProbleme#309, ubtue/DatenProbleme#307, ubtue/DatenProbleme#306, ubtue/DatenProbleme#300, ubtue/DatenProbleme#264, ubtue/DatenProbleme#262, ubtue/DatenProbleme#258
=> More Zotero changes

cpp/data/zts_harvester.conf, cpp/lib/include/Zotero.h, cpp/lib/src/Zotero.cc, cpp/zts_harvester.cc
refs ubtue/DatenProbleme#323, ubtue/DatenProbleme#311, ubtue/DatenProbleme#303
=> zts_harvester: add support for suppressing metadata fields

cpp/.gitignore, cpp/archive_sent_records.cc, cpp/data/zts_harvester.conf, cpp/lib/include/JSON.h, cpp/lib/include/JournalConfig.h, cpp/lib/include/Zotero.h, cpp/lib/src/JournalConfig.cc, cpp/lib/src/SimpleCrawler.cc, cpp/lib/src/Zotero.cc, cpp/zeder_to_zotero_conversion_tools.cc, cpp/zts_harvester.cc
goes with ubtue/zotero-translators#90
=> Zotero crawling omnibus pull request

cpp/data/zts_harvester.conf
refs ubtue/DatenProbleme#398, ubtue/DatenProbleme#410, ubtue/DatenProbleme#408, ubtue/DatenProbleme#407, ubtue/DatenProbleme#406, ubtue/DatenProbleme#404, ubtue/DatenProbleme#401, ubtue/DatenProbleme#400, ubtue/DatenProbleme#405, ubtue/DatenProbleme#399
=> Dateprobleme fixes

cpp/Makefile.inc, cpp/lib/Makefile, cpp/lib/src/FullTextImport.cc
See https://lemire.me/blog/2018/07/25/it-is-more-complicated-than-i-thought-mtune-march-in-gcc/
and http://august.nagro.us/optimized-openjdk.html in order to understand this.
=> Attempt at creating faster executables.

cpp/data/zotero_harvester.conf
=> zotero_harvester.conf: Changed RSS feed url for 2011-9771

cpp/data/convert_json_to_marc.README
=> Attempted to fully document all possible settings in config files

cpp/lib/include/ZoteroHarvesterUtil.h, cpp/lib/src/ZoteroHarvesterUtil.cc
My internet is working for the moment (it's still very intermittent; won't have anything stable until Monday), so I took the opportunity to write to Johannes Rield to restart my work machine. This fixed the issue I had with the remote connection, and I was therefore able to look into the hung up zotero_harvester processes on Nu.
The problem was not a deadlock but a process-wide SIGSTOP handler that was supposed to be used for debugging. I put it in the Zotero logger code in early March to help with debugging a corner-case where a pre-condition was failing. Turns out it was due to a hash collision. To go into detail: The Zotero logger tracks active Zotero tasklets, each of which run in its own thread, to sort incoming log statements. Originally, this was done by mapping the tasklet's …
=> Zotero MT fixes

cpp/installer.cc
Needed e.g. for import_zeder_changes_into_zotero_harvester_config.sh
=> installer github-robot ssh keys

cpp/lib/src/ZoteroHarvesterConversion.cc
…to reflect new swb website structure
=> ZoteroHarvesterConversion.cc: Changed regex in AUTHOR_PPN_MATCHER

cpp/lib/include/ZoteroHarvesterConfig.h, cpp/lib/src/ZoteroHarvesterConfig.cc, cpp/lib/src/ZoteroHarvesterConversion.cc
See also:
https://github.com/ubtue/zotero-enhancement-maps/commit/14b8f76ac9b14fdc67e24562d9c459681063546
https://github.com/ubtue/zotero-enhancement-maps/commit/f6723e8c98fe5359ac8d8231e452ca60f4668037
=> Zotero Author lookups 

cpp/merge_differential_and_full_marc_updates.sh
Fixed invalid parameters in "wc" call.
Been in there for 6 months and nobody noticed!
=> merge_differential_and_full_marc_updates.sh

cpp/.gitignore, cpp/throwaways/.gitignore, cpp/zotero_enhancement_maps_generator.cc
- not added to cronjob yet
- using C++17 features for map iteration
=> zotero_enhancement_maps_generator

cpp/lib/src/ZoteroHarvesterConversion.cc, cpp/validate_harvested_records.cc
@ruschein: Please review!
DRAFT => Coding finished, but merging maybe needs to be coordinated with migration of zotero_harvester.conf (still needs to be discussed in issue)
=> zotaut language detection + validate harvested records

cpp/data/installer/ub_tools.sql, cpp/data/sql_updates/ub_tools.15, cpp/data/sql_updates/ub_tools.16, cpp/lib/src/ZoteroHarvesterUtil.cc, cpp/missing_metadata_db_tool.cc, cpp/validate_harvested_records.cc, cpp/zotero_harvester.cc
Merge needs to wait until zeder_journals has been populated on nu+ub28
=> Foreign Keys on zeder_journals.id

cpp/pipelines/ixtheo_marc_pipeline_fifo.sh
=> Death to trailing period for keywords!

cpp/.gitignore, cpp/cgi_progs/.gitignore, cpp/cgi_progs/Makefile, cpp/cgi_progs/ini_validator.cc, cpp/data/NewsletterUploadForm.html, cpp/installer.cc, cpp/lib/include/util.h, cpp/marc_tools/.gitignore, cpp/pipelines/.gitignore, cpp/throwaways/Makefile
logger->redirectOutput not working. No error calling it, but the Program will abort and the message will neither be on stdout nor in apache error.log anymore.
=> cgi_progs/ini_validator.cc

cpp/lib/include/ZoteroHarvesterConfig.h, cpp/lib/src/ZoteroHarvesterConfig.cc, cpp/lib/src/ZoteroHarvesterConversion.cc, cpp/zeder_to_zotero_importer.cc
After merge, don't forget to remove `-?-` values from conf before pulling, and pull before next zeder_to_zotero_importer cronjob is run!
=> zotaut language normalization

cpp/update_zotero_enhancement_maps.sh
- Wait until change is confirmed by @socheres
- Don't forget to update wiki after merge
=> update_zotero_enhancement_maps.sh: Added ENTRY_POINT_URL to FIELDS_TO_UPDATE

cpp/lib/include/ZoteroHarvesterConversion.h, cpp/lib/include/ZoteroHarvesterZederInterop.h, cpp/lib/src/ZoteroHarvesterConversion.cc, cpp/lib/src/ZoteroHarvesterZederInterop.cc, cpp/zeder_to_zotero_importer.cc, cpp/zotero_harvester.cc
i will update wiki after PR is merged
=> zotaut changes

cpp/lib/include/ZoteroHarvesterConfig.h, cpp/lib/include/ZoteroHarvesterConversion.h, cpp/lib/src/ZoteroHarvesterConfig.cc, cpp/lib/src/ZoteroHarvesterConversion.cc, cpp/zotero_harvester.cc
implementation is now complete but untested
=> zotaut: global ZoteroMetadataParams & MarcMetadataParams

cpp/cgi_progs/zotero_cgi.cc, cpp/lib/include/DbConnection.h
FYI, urgent fix, will merge myself
=> zotero_cgi: Register missing journals in DB

cpp/cgi_progs/zotero_cgi.cc, cpp/data/installer/ub_tools.sql, cpp/data/sql_updates/ub_tools.23, cpp/data/zotero_cgi/delivered.html, cpp/lib/include/ZoteroHarvesterUtil.h, cpp/lib/src/ZoteroHarvesterUtil.cc
DRAFT
- incomplete implementation ("ignore" will not be set automatically yet)
- still needs to be discussed with @socheres
=> zotero_harvester: Additional DeliveryStates "ignore" and "reset"

cpp/cgi_progs/zotero_cgi.cc, cpp/data/installer/ub_tools.sql, cpp/data/sql_updates/ub_tools.25, cpp/data/zotero_cgi/qa.html
=> zotero_cgi: QA view refactoring

cpp/validate_harvested_records.cc
=> validate_harvested_records.cc fixes

cpp/cgi_progs/zotero_cgi.cc, cpp/data/zotero_cgi/delivered.html
=> zotero_cgi: Reset already delivered records

cpp/data/rss_email.template.de
The text was proposed by @relhei.
=> Added rss_email.template.de

cpp/data/sql_updates/vufind.5
=> vufind.5: Fix problem with tuefind_uuid TRIGGER in MariaDB

cpp/extract_conspicouus_names_from_zota.cc
@jriedl FYI, had problems when pulling on ptah
=> extract_conspicouus_names_from_zota.cc: Solve compiler problem under CentOS 8

cpp/data/sql_updates/vufind.6
should be merged together with ubtue/tuefind#1514
=> authority-related database changes

cpp/data/sql_updates/vufind.7, cpp/new_journal_alert.cc, cpp/throwaways/get_krim_keyword_frequency.cc
Not yet finished, so please don't merge
=> Extract frequencies

java/solrmarc_mixin/Makefile, java/solrmarc_mixin/src/de/unituebingen/ub/ubtools/solrmarcMixin/TuelibBiblioMixin.java, java/solrmarc_mixin/src/de/unituebingen/ub/ubtools/solrmarcMixin/TuelibMixin.java
ubtue/tuefind#1552 should be merged before merging this one.
=> TuelibBiblioMixin: Use new tuefind CreatorTools

cpp/lib/include/MARC.h, cpp/lib/src/MARC.cc, cpp/pipelines/add_authority_wikidata_ids.cc
changed wikidata id extraction and wikipedia link extraction to prevent dupplicates
=> changed wikidata id and wikipedia link extraction

cpp/pipelines/patch_ppns_in_databases.cc
=> patch_ppns_in_databases: Also consider 889w

cpp/lib/include/DbConnection.h, cpp/lib/src/DbConnection.cc, cpp/pipelines/patch_ppns_in_databases.cc
=> patch_ppns_in_databases.cc: Extended reporting for "report_only" flag

cpp/data/bibstudies-beacon.header, cpp/data/canonlaw-beacon.header, cpp/data/ixtheo-beacon.header, cpp/data/new_journal_alert_email.template.de, cpp/data/new_journal_alert_email.template.en, cpp/new_journal_alert.cc
(PR also contains some minor BEACON template changes)
=> new_journal_alert: mail templates depending on user language

cpp/data/system_updates/111.vufind.sql
system_update for ubtue/tuefind#2046
=> 111.vufind.sql: Add column "external_document_guid" to tuefind_publications table

cpp/data/system_updates/114.vufind.sql, cpp/data/system_updates/115.vufind.sql
This pull request MUST be merged together with ubtue/tuefind#2071
=> vufind db updates

cpp/data/system_updates/120.vufind.sql
belongs together with ubtue/tuefind#2260
=> DB patch for user license locking mechanism

cpp/lib/include/Downloader.h, cpp/lib/src/Downloader.cc
- can be easily tested against dummy websites, e.g. http://httpstat.us/501
=> Downloader error detection

cpp/pipelines/krimdok_marc_pipeline.sh
add 'Add Wikidata IDs to Authority Data' using the add_authority_external_ref program in the script file 'krimdok_marc_pipelines.sh'
=> 'Add Wikidata IDs to Authority Data' in the krimdok_marc_pipelines

cpp/marc_tools/marc_augmentor.cc
Example:
- marc_augmentor input_file_name output_file_name --replace-field-if-regex '007:/^(.*)$/HELLO_\1/' '007:'
- marc_augmentor input_file_name output_file_name --replace-field-if-regex '007:/^(.*)$/HELLO_\1/' '007:tu'
=> add a new feature '--replace-field-if-regex' in marc_augmentor

cpp/harvest/issn_lookup.py, cpp/harvest/remid.sh
update remid.sh to put the temp files into /tmp. update issn_lookup.py to use \r in the description for display
=> update remid.sh and issn_lookup.py

cpp/pipelines/collect_journal_stats.cc
(since it will be POSTed to the upload form instead)
=> collect_journal_stats.cc: Remove "Systemtyp" from JSON

cpp/installer.cc
fixing errors when importing the store procedure from the SQL file
=> Updating installer 

cpp/lib/src/IssnLookup.cc
remove unwanted hidden code in title
=> adding TitleNormalization function

cpp/installer.cc, java/solr_plugins/MultiLanguageQueryParser/src/de/uni_tuebingen/ub/ixTheo/MultiLanguageQueryParser.java, java/solr_plugins/PrefixSortFacetten/src/de/uni_tuebingen/ub/ixTheo/handler/component/FacetPrefixSortComponent.java, java/solr_plugins/RangedSearches/src/de/uni_tuebingen/ub/ixTheo/bibleRangeSearch/BibleRangeWeight.java, java/solr_plugins/RangedSearches/src/de/uni_tuebingen/ub/ixTheo/rangeSearch/RangeQuery.java, java/solr_plugins/RangedSearches/src/de/uni_tuebingen/ub/ixTheo/rangeSearch/RangeWeight.java
Belongs together with ubtue/tuefind#2576
=> TueFind 9.0

cpp/data/system_updates/150.ixtheo.sql, cpp/data/system_updates/150.vufind.sql, cpp/data/system_updates/151.krim_translations.sql
=> Angabe Land im Benutzerkonto (für KrimDok)

cpp/installer.cc, docker/ub_tools/Dockerfile, docker/ub_tools/Makefile
@steven-lolong : This should work fine so please merge. Afterwards, you will get more errors from scripts which are used outside of installer.cc, for example: 
So please continue the cleanup from this point.
=> docker/ub_tools: Improve Makefile & Dockerfile

cpp/data/installer/ixtheo.cronjobs, cpp/data/system_updates/157.sh, cpp/rss_aggregator.cc
Downloads RSS Feeds when --use-web-proxy is set and generates a subsystem specific xml file based on the provided subsystem. Updated the cronjob accordingly and created a shell script for the system_update.
=> Adjust rss_aggregator and update cronjob

cpp/data/installer/krimdok.cronjobs, cpp/data/system_updates/158.sh
I've set the time to 22:10 o'clock, let me know if you'd prefer a different time. The Cronjob has been tested locally.
See https://github.com/ubtue/tuefind/pull/3248 for the enabled vufind SDI.
=> Adding cronjob to alert on new search results in KrimDok

java/solr_plugins/MultiLanguageQueryParser/src/de/uni_tuebingen/ub/ixTheo/MultiLanguageQueryParser.java
Compatibility for the system that uses filter query (fq) without using the MultilanguageQueryParser in a specific way, i.e., KrimDok.
=> Compatibility for the system that uses filter query (fq) without using the MultilanguageQueryParser.

cpp/lib/src/ZoteroHarvesterConfig.cc, cpp/lib/src/ZoteroHarvesterConversion.cc
See: https://github.com/ubtue/DatenProbleme/issues/2271
=> Handle uppercase letters in language normalization
