ubtue/ub_tools

cpp/lib/DirectoryEntry.cc
cpp/lib/DirectoryEntry.h

there seem to be compiler differences between the compiler that we use
on Ubuntu and the one that we use on Centos.

Explicitly implemented a move constructor for class DirectoryEntry as

---

cpp/Makefile
cpp/marc_grep.cc

if multiple tags are being emitted for a record they will now be in
alphanumerical order.

Now marc_grep, formerly known as marc_grep2, sorts its output.  That is

---

.gitignore
cpp/Makefile
cpp/update_ixtheo_notations.cc

made the renamed program write colon-separated ixTheo notations
in the 652$a subfield.

Renamed ixtheo_notation_stats to update_ixtheo_notations and

---

solr_plugins/Bibelstellensuche/src/de/uni_tuebingen/ub/ixTheo/bibleRangeSearch/Range.java
solr_plugins/Bibelstellensuche/tests/de/uni_tuebingen/ub/ixTheo/bibleRangeSearch/ScoreTest.java

The algorithm is:
( Min(a.upper, b.upper) - Max(a.lower, b.lower)  ) / ( Max(a.upper, b.upper) - Min(a.lower, b.lower) )
Let's say the range [lower, upper] a = [2, 2] and b = [1, 5].
=> ( Min(2, 5) - Max(2, 1)  ) / ( Max(2, 5) - Min(2, 1) )
=> ( 2 - 2  ) / ( 5 - 1)
=> 0
So a bible range should have a thickness.

Fixing bible range bug.

---

cpp/lib/include/PriorityQueue.h

access to the underlying container.

Our very own priority queue, that unlike the one from the STL, grants

---

cpp/data/installer/scripts/install_centos_packages.sh
cpp/data/installer/scripts/install_ubuntu_packages.sh

- mcrypt no longer needed since Vufind4 (and module will no longer be available in PHP7.2)
- dev not needed, because we don't develop PHP modules (package takes > 200MB!)

removed obsolete PHP dependencies

---

cpp/data/zotero_cgi/index.html
cpp/data/zotero_cgi/scripts.js
cpp/data/zts_harvester.conf
cpp/lib/include/SimpleCrawler.h
cpp/lib/include/Zotero.h
cpp/lib/src/MARC.cc
cpp/lib/src/SimpleCrawler.cc
cpp/lib/src/Zotero.cc
cpp/rss_harvester.cc
cpp/zotero_cgi.cc
cpp/zts_client.cc
cpp/zts_harvester.cc

SiteDesc was the wrong place, because it is Crawling specific and we want something usable by Crawling+RSS, so i introduced AugmentParams.
Also fixed a time problem, see:
https://stackoverflow.com/questions/19524720/using-strptime-converting-string-to-time-but-getting-garbage
ISSN not working yet.... multiple optional parameters can not be passed due to current zts_client config file structure. Also, strptime_format not working with RSS yet.

optional strptime_format for Zotero

---

cpp/data/zts_harvester.conf
cpp/lib/include/MARC.h
cpp/lib/src/TimeUtil.cc
cpp/lib/src/Zotero.cc
cpp/zts_harvester.cc

Turns out the "%:z" format specifier works with the built-in date command but not with strptime :man_facepalming: I just went with the original plan of matching the date string with the expect format in the standard and stripping out the colon.

Another attempt at fixing the strptime bug

---

cronjobs/util.py

use search() instead of match() if string is not required to begin at position 0, see
https://docs.python.org/2/library/re.html#re.RegexObject.search

fixed python regex problem

---

cpp/journal_publishing_processor.cc
cpp/lib/include/ControlNumberGuesser.h
cpp/lib/include/FullTextImport.h
cpp/lib/src/ControlNumberGuesser.cc
cpp/lib/src/FullTextImport.cc

Unfortunately, the new additions are broken. With the year constraint, we seem to be dropping _all_ records. Will need to be investigated.

add support for publication year whilst importing full text

---

cpp/archive_records.cc
cpp/lib/src/Zotero.cc

use 773t instead of 773a when generating MARC in Zotero context

---

cpp/lib/src/Zotero.cc

zotero: trim all whitespaces in tags before writing to 650$a (including Unicode characters)

---

cpp/lib/include/XmlWriter.h
cpp/lib/src/FileUtil.cc
cpp/rss_aggregator.cc

Clarify ownership rules in XmlWriter c'tor
Fix memory-leak in FileUtil::GetGetPathFromFileDescriptor

rss_aggregator: fix temp file path, fix double-free

---

cpp/lib/src/ExecUtil.cc
cpp/lib/src/SystemdUtil.cc

Old version also didnt't work under CentOS, because original command name is not "systemd" but something like "/usr/lib/systemd/systemd --switched"

improved SystemdUtil::IsAvailable

---

cpp/lib/include/ZoteroHarvesterConfig.h
cpp/lib/src/ZoteroHarvesterConfig.cc
cpp/zeder_to_zotero_importer.cc
cpp/zotero_harvester.cc

ToDo before enabling cronjob:
- rename "newly_synced_entry"? (e.g. "newly_imported_entry")
- add documentation for "newly_synced_entry" to zotero_harvester.conf
- prevent automatic delivery of entries marked as "newly_synced_entry"

zeder_to_zotero_importer: zeder_newly_synced_entry

---

cronjobs/util.py

FYI, this should fix the following error:
```
/usr/local/bin/fetch_interlibraryloan_ppns.py: fetch_interlibraryloan_ppns.py.GetDataFromGVI: GVI gateway timeout out after 120 seconds!
Failed to send your email: {'ixtheo-team@uni-tuebingen.de': (550, b'5.1.1 <ixtheo-team@uni-tuebingen.de>: Recipient address rejected: User unknown in virtual alias table')}
```

util.py: change default email recipient

---

cpp/lib/src/ZoteroHarvesterZederInterop.cc
cronjobs/update_zotero_enhancement_maps.sh

Use Zeder field "sprz" instead of "spr" for EXPECTED_LANGUAGES & enable auto-sync

zeder_to_zotero_importer

---

cpp/data/installer/ub_tools.sql
cpp/data/sql_updates/ub_tools.22

- fixed syntax
- renamed keys to reflect column change. needed to re-create foreign key as well because other constraint was used in foreign key

ub_tools.sql: fix for ub_tools.22

---

cpp/cgi_progs/zotero_cgi.cc
cpp/data/zotero_cgi/delivered.html
cpp/data/zotero_cgi/style.css
cpp/lib/include/ZoteroHarvesterConfig.h
cpp/lib/include/ZoteroHarvesterDownload.h
cpp/lib/src/ZoteroHarvesterConfig.cc
cpp/lib/src/ZoteroHarvesterConversion.cc
cpp/lib/src/ZoteroHarvesterDownload.cc
cpp/lib/src/ZoteroHarvesterUtil.cc

- remove * from zotero_expected_languages in zotero_harvester.conf directly after merging this
- also tell socheres to remove * from Zeder

zotaut: Changes to automatic language detection (+performance settings)

---

cpp/lib/include/HtmlUtil.h
cpp/lib/src/HtmlUtil.cc
cpp/rss_aggregator.cc

... not sure if it is necessary to improve the algorithm (e.g. skip entities and multibyte characters)

rss_aggregator: Limit item description to 500 characters

---

cpp/lib/src/TranslationUtil.cc

Columns have been in the wrong order for this language, see:
https://de.wikipedia.org/wiki/Liste_der_ISO-639-1-Codes

TranslationUtil.cc: Swap values for msa+may

---

cpp/data/installer/scripts/install_centos_packages.sh

Existing installations under CentOS are currently removed each time a make install is executed, because /usr/local/bin is deleted

install_centos_packages.sh: Use old composer version (1.x) to avoid compatibility problems

---

cpp/data/rss_aggregator.conf
cpp/lib/src/SyndicationFormat.cc
cpp/rss_aggregator.cc

https://www.data2type.de/xml-xslt-xslfo/newsfeeds-rss-atom/rss-2-0-und-vorgaengerversionen/multimediadaten-mit-enclosure/

RSS: added new feed + support for "enclosure" element

---

cpp/data/installer/ixtheo.cronjobs
cpp/data/installer/ub_tools.sql
cpp/data/rss_aggregator_relbib.conf
cpp/data/sql_updates/ub_tools.26
cpp/rss_aggregator.cc

Changes:
- renamed rss_aggregator.conf to rss_aggregator_relbib.conf
- fixed a bug where optional config_file_path not having any effect
- rss_aggregator now takes mandatory arg for config_file_path
- add new db column "flavour" + setting in rss_aggregator.conf
- simply use default db credentials from ub_tools.conf
Notes:
- DB unique key is still "item_id" (could not be combined with flavour due to length issues), so using the same items in multiple flavours is not supported.
This PR should be merged together with ubtue/tuefind#1398. Don't forget to change crontab after pull.

rss_aggregator

---

cpp/lib/include/ZoteroHarvesterConfig.h
cpp/lib/include/ZoteroHarvesterConversion.h
cpp/lib/src/ZoteroHarvesterConfig.cc
cpp/lib/src/ZoteroHarvesterConversion.cc

- follow-up PR to #3805
- Allow multiple languages in MetadataRecord => multiple changes necessary to allow this
- Renamed+Splitted the very large DetectLanguage function into several smaller functions to make things clearer
- Added support for '!' and '?'
- Still keep backwards compatibility for non-merged force_language_detection entries

zotaut language detection '!' and '?'

---

cpp/zotaut/validate_harvested_records.cc

not supported by current clang-Version in CentOS8

validate_harvested_records.cc: Revert C++20 feature contains()

---

cpp/marc_tools/single_marc_convert_keywords.cc

I wasn't sure whether that was the approach you were looking / hoping for.
The issue with the approach of a second map mapping ppn and tags was that there would be multiple entries for the same ppn mapping to all the tags, meaning we wouldn't be able to filter the right tags anymore. At least that's how I understood it.
Therefore I added the tag information to the keywords_to_gnd_numbers_map 's value, which in return means it'll show up in the output file for matching keywords. If this outcome is not desirable, just ignore this PR.

additional log info for matched tag number

---

cpp/data/installer/boot_notification.service

Without this section, `systemctl enable boot_notification.service` will produce a warning and the service will not be enabled for being executed after reboot:
```
The unit files have no installation config (WantedBy, RequiredBy, Also, Alias
settings in the [Install] section, and DefaultInstance for template units).
This means they are not meant to be enabled using systemctl.
Possible reasons for having this kind of units are:
1) A unit may be statically enabled by being symlinked from another unit's
.wants/ or .requires/ directory.
2) A unit's purpose may be to act as a helper for some other unit which has
a requirement dependency on it.
3) A unit may be started when needed via activation (socket, path, timer,
D-Bus, udev, scripted systemctl call, ...).
4) In case of template units, the …
```

boot_notification.service: Added [Install] section

---

cpp/data/installer/ixtheo.sql
cpp/installer.cc

@jriedl: We will merge this to solve a problem during the installation of the new test server. Also, we found some documentation saying that CREATE TEMPORARY TABLES is already part of ALL PRIVILEGES in database context. Please have a short look at it anyway when time permits, just to make sure there will be no ubuntu-related problems later.

installer.cc: Moved granting of privileges from ixtheo.sql to installer.cc

---

docker/Makefile.inc
docker/ixtheo-ubuntu/Makefile
docker/krimdok-ubuntu/Makefile

... this way we save about 10 GB of data which no longer need to be copied each time we build a docker container.

docker: Shared Makefile.inc for ixtheo-ubuntu & krimdok-ubuntu (+reduced amount of data copied from /mnt)

---

cpp/data/system_updates/109.vufind.sql

belongs to ubtue/tuefind#2035
table wasn't use in live mode yet, so it will simply be dropped & re-created with the new schema.

109.vufind.sql: system update for vufind.tuefind_publications table

---

docker/ixtheo/apache2/vufind-bibstudies.conf
docker/ixtheo/apache2/vufind-churchlaw.conf
docker/ixtheo/apache2/vufind-ixtheo.conf
docker/ixtheo/apache2/vufind-relbib.conf
docker/krimdok/apache2/vufind-krimdok.conf

Refers to ubtue/tuefind#2309 but should be backwards compatible.

VuFind 8.1: Add new "assets" directory to apache configuration in docker images

---

cpp/harvest/core.cc

Fixing the error regarding the number of affected data.
See.
https://en.cppreference.com/w/cpp/algorithm/set_intersection

Sort the filter data and the target data provider id before check the intersection

---

docker/krimdok/local_overrides/krimdok_kfl.conf

docker/krimdok: Include dummy local_overrides/krimdok_kfl.conf
